auth:
  adminUser: admin
  existingSecret: keycloak-admin
  passwordSecretKey: admin-password

service:
  type: ClusterIP

metrics:
  enabled: true
  serviceMonitor:
    enabled: false

postgresql:
  enabled: true
  auth:
    existingSecret: keycloak-postgresql
    secretKeys:
      userPasswordKey: password

