servingEngineSpec:
  runtimeClassName: ""
  modelSpec:
    - name: opt125m
      repository: vllm/vllm-openai
      tag: latest
      modelURL: facebook/opt-125m
      chatTemplate: chat.jinja2
      chatTemplateConfigMap: |-
        {% for message in messages %}
        {% if message['role'] == 'system' %}System: {{ message['content'] }}
        {% elif message['role'] == 'user' %}User: {{ message['content'] }}
        {% elif message['role'] == 'assistant' %}Assistant: {{ message['content'] }}
        {% endif %}
        {% endfor %}
        {% if add_generation_prompt %}Assistant: {% endif %}
      replicaCount: 1
      requestCPU: 1
      requestMemory: 2Gi
      requestGPU: 1
  serviceMonitor:
    enabled: false

routerSpec:
  enableRouter: true
  serviceType: ClusterIP
  servicePort: 80
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
  routingLogic: session
  sessionKey: x-user-id
  serviceMonitor:
    enabled: false
