
masterkey: sk-1234
proxy_config:
  model_list:
    # At least one model must exist for the proxy to start.
    - model_name: gpt-3.5-turbo
      litellm_params:
        model: gpt-3.5-turbo
        api_key: eXaMpLeOnLy
    - model_name: fake-openai-endpoint
      litellm_params:
        model: openai/fake
        api_key: fake-key
        api_base: https://exampleopenaiendpoint-production.up.railway.app/
    - model_name: vllm-models
      litellm_params:
        model: openai/facebook/opt-125m # the `openai/` prefix tells litellm it's openai compatible
        api_base: http://0.0.0.0:4000/v1
        api_key: none
        rpm: 1440
      model_info: 
        version: 2
  general_settings:
    master_key: os.environ/PROXY_MASTER_KEY
    store_model_in_db: true
    store_prompts_in_spend_logs: true
  litellm_settings:
    cache: True
    callbacks: ["prometheus"]
    
db:
  # Use an existing postgres server/cluster
  useExisting: true
  # How to connect to the existing postgres server/cluster
  endpoint: postgresql.default.svc.cluster.local
  secret:
    name: litellm-dbcredentials
  # Use the Postgres Helm chart to create a single node, stand alone postgres
  #  instance.  See the "postgresql" top level key for additional configuration.
  deployStandalone: false
redis:
  deployStandalone: false
  enabled: true
  host: "redis.default.svc.cluster.local" 
  secret:
    name: redis
    passwordKey: redis-password
migrationJob:
  enabled: false