ollama:
  # -- Automatically install Ollama Helm chart from https://otwld.github.io/ollama-helm/. Use [Helm Values](https://github.com/otwld/ollama-helm/#helm-values) to configure
  enabled: false
tika:
  # -- Automatically install Apache Tika to extend Open WebUI
  enabled: true
openaiBaseApiUrl: "http://litellm.default.svc.cluster.local:4000/v1"
