servingEngineSpec:
  runtimeClassName: ""
  modelSpec:
  - name: "gemma-3-1b-it"
    repository: "lmcache/vllm-openai"
    tag: "latest"
    modelURL: "google/gemma-3-1b-it"
    replicaCount: 2
    requestCPU: 4
    requestMemory: "12Gi"
    requestGPU: 1
    hf_token: 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
    pvcStorage: "40Gi"
    pvcAccessMode:
      - ReadWriteMany
    storageClass: "" #This is to let helm pvc know it should be empty string
    vllmConfig:
      enableChunkedPrefill: false
      enablePrefixCaching: false
      maxModelLen: 32768
      dtype: "bfloat16"
      extraArgs: ["--disable-log-requests", "--gpu-memory-utilization", "0.8"]
    lmcacheConfig:
      enabled: true
      cpuOffloadingBufferSize: "10"

routerSpec:
  resources:
  requests:
    cpu: "2"
    memory: "4G"
  routingLogic: "session"
  sessionKey: "x-user-id"

cacheserverSpec:
  replicaCount: 1
  containerPort: 8080
  servicePort: 81
  serde: "naive"
  repository: "lmcache/vllm-openai"
  tag: "latest"
  resources:
    requests:
      cpu: "2"
      memory: "6G"
    limits:
      cpu: "4"
      memory: "10G"
  labels:
    environment: "cacheserver"
    release: "cacheserver"